config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :dashboard
  resources :users
  resources :transactions
  resources :friends
  resources :memberships

   root to: 'home#index'

end

app/models/friend.rb
class Friend<ActiveRecord::Base
  has_many :memberships
  has_many :users, through: :memberships
end

app/models/membership.rb
class Membership<ActiveRecord::Base
  belongs_to :user
  belongs_to :friend
end

app/models/transaction.rb
class Transaction<ActiveRecord::Base
  belongs_to :payee, class_name: "User", foreign_key: "payee_id"
  belongs_to :payer, class_name: "User", foreign_key: "payer_id"

  validates :payee, presence: true
  validates :payer, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :credits, class_name: "Transaction", foreign_key: "payee_id"
  has_many :debits, class_name: "Transaction", foreign_key: "payer_id"
  has_one :membership
  has_one :friend, through: :membership



  def credit_total
    if self.credits.empty?
      return 0
    else
      credits_array = []
      self.credits.each do |credit|
        credits_array << credit.amount
      end
      credits_array.inject { |sum, amount| sum + amount }
    end
  end

  def debit_total
    if self.debits.empty?
      return 0
    else
      debits_array = []
      self.debits.each do |debit|
        debits_array << debit.amount
      end
      debits_array.inject { |sum, amount| sum + amount }
    end
  end

  def balance
    credit_total - debit_total
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController<ApplicationController
  before_filter :authenticate_user!

  def index
    @transactions = Transaction.all
    @friend_group = current_user.friend
  end

end

app/controllers/friends_controller.rb
class FriendsController<ApplicationController
  before_filter :authenticate_user!
  def index
    @groups = Friend.all
  end

  def new
    @friend_group = Friend.new
  end

  def create
    @friend_group = Friend.create(friend_group_params)
    if @friend_group.save
      redirect_to @friend_group
    else
      render action: 'new'
    end
  end

  def show
    @friend_group = Friend.find(params[:id])
    @membership = Membership.new
  end



  private
  def friend_group_params
    params.require(:friend).permit(:group_name)
  end
end

app/controllers/home_controller.rb
class HomeController <ApplicationController


  def index
    if user_signed_in?
      redirect_to dashboard_index_path
    end
  end

end

app/controllers/memberships_controller.rb
class MembershipsController<ApplicationController
  def create
    @membership = Membership.create(membership_params)
    @membership.save
    redirect_to dashboard_index_path
  end

  def new
    @membership = Membership.new
  end



  private
  def membership_params
    params.require(:membership).permit(:user_id, :friend_id)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController<ApplicationController
  def index
    @user = current_user
  end

  def new
    @users = User.all
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.create(transaction_params)
    @transaction.save
    redirect_to dashboard_index_path
  end

  def destroy
    Transaction.find(params[:id]).destroy
    redirect_to dashboard_index_path
  end

  private

  def transaction_params
    params.require(:transaction).permit(:payer_id, :payee_id, :amount)
  end

end

app/controllers/users_controller.rb
class UsersController<ApplicationController
  def index
    @users = User.all
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<div class="row dashboard">

    <div class="row">
      <div class="large-5 medium-5 small-12 columns">
        <h4><%= current_user.email %></h4>
        <%= image_tag("http://i0.kym-cdn.com/photos/images/newsfeed/000/173/576/Wat8.jpg?1315930535", class: "profile-picture") %>
        <h3 class="show-for-small"><%= current_user.email %><hr/></h3>
        <div class="progress [small-# large-6] [secondary alert success] [radius round]">
          <span class="meter" style="width: 15%; background-color: green;"></span>
        </div>
        <ul>
          <li>Owes: $<%= current_user.debit_total %></li>
          <li>Owed: $<%= current_user.credit_total %> </li>
          <li>Balance: $<%= current_user.balance %></li>
        </ul>
      </div>

      <div class="large-7 medium-7 small-12 columns">


        <table>
          <% if @friend_group %>
            <h2><%= @friend_group.group_name %></h2>
            <thead>
              <tr>
                <th width="50">User</th>
                <th width="150">Balance</th>
              </tr>
            </thead>
            <tbody>
              <% @friend_group.users.each do |u| %>
                <tr>
                  <td><%= u.email %></td>
                  <td><%= u.balance %></td>
                </tr>
              <% end %>
            </tbody>

          <% else %>
              <h2>Not in friend group</h2>
          <% end %>

        </table>
        <%= link_to "Add transaction", new_transaction_path, class: "small-12 medium-7 large-7 button" %>
        <%= link_to "View transactions", transactions_path, class: "small-12 medium-7 large-7 button" %>
      </div>
    </div>







</div>

app/views/friends/index.html.erb
<h1>Friends</h1>

<%= link_to "Add new friend group", new_friend_path, class: "small-12 large-6 button" %>

<% @groups.each do |group| %>
  <li><%= link_to  group.group_name, group %></li>

<% end %>

app/views/friends/new.html.erb
<h1>Create new friend group</h1>

<%= form_for @friend_group, url: { action: "create"} do |f| %>
  <p>
    <%= f.label :group_name, "Group name" %>
    <%= f.text_field :group_name %>
  </p>
    <%= f.submit "Create" %>
<% end %>

app/views/friends/show.html.erb
<h1><%= @friend_group.group_name %></h1>


<!--  Users is not being picked up-->
<% @friend_group.users.each do |user| %>
  <li><%= user.email %></li>
<% end %>


<%= form_for @membership, url: { controller: "memberships", action: "create" } do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :friend_id, value: @friend_group.id %>
  <%= f.submit "Join this group!" %>
<% end %>

app/views/home/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <%= image_tag("cash-logo.png") %>
  </div>
</div>




<div class="row">
  <div class="large-12 centered-columns">
    <ul class="button-group round even-2">
      <li><%= link_to("Sign up" , new_user_registration_path, { class: "button home" }) %></li>
      <li><%= link_to("Sign in" , new_user_session_path, { class: "button home" }) %></li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CashOnly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- ADD TOP BAR, WRAP CONTENT INSIDE -->




  <nav class ="top-bar" id ="user_nav">
    <ul class="title-area">
      <li class ="name">
        <h1><%= link_to("Ca$h Only", root_path) %></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a>
    </ul>

    <section class="top-bar-section">
      <ul class="left">
        <li class="divider"></li>
          <% if !current_user %>
            <li class="active"><%= link_to("Sign in" , new_user_session_path) %></li>
            <li><%= link_to("Sign up" , new_user_registration_path) %></li>
          <% else %>
            <li class="active"><%= link_to(current_user.email , dashboard_index_path) %></li>
            <li><%= link_to("Sign out", destroy_user_session_path, method: :delete) %></li>
            <li><a href="#">About</a></li>
            <li><%= link_to("Friends", friends_path)%></li>
          <% end %>
        <li class="divider"></li>
        <li class="divider"></li>
      </ul>
    </section>

  </nav>


  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>






<!--
    <% if !current_user %>
    <div>
      <%= link_to("Sign up" , new_user_registration_path) %>
    </div>
    <div>
      <%= link_to("Sign in" , new_user_session_path) %>
    </div>
    <% else %>
    <div>
      Signed in as <%= current_user.email %>
    </div>
    <div>
      <%= link_to("Sign out", destroy_user_session_path, method: :delete) %>
    </div>
    <% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p> -->


<%= yield %>


<footer class="row">
  <div class="large-12 columns">
    <hr/>
    <div class="row">
      <div class="large-6 columns">
        <!-- PROBLEM WITH LINKS WRAPPING UNDER -->
        <p>© Copyright 2014 Nathan Burgess</p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><a href="https://github.com/NB28VT">Github Page</a></li>
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>










</body>
</html>

app/views/transactions/index.html.erb
<div class="large-12 colummns transaction">

  <h3>Your transactions</h3>

  <table class="large-12 columns">
    <thead>
      <tr>
        <th width="100">Amount</th>
        <th width="100">Date</th>
        <th>Description</th>
        <th width="150">Owed by</th>
        <th width="150">Owed to</th>
        <th width="150">Delete</th>
      </tr>
    </thead>
    <tbody>
      <h3>Debts</h3>
        <% if @user.debits != nil %>
          <% @user.debits.each do |t| %>
            <tr>
              <td><%= t.amount %></td>
              <td><%= t.created_at %></td>
              <td><%= t.description %></td>
              <td><%= t.payer_id %></td>
              <td><%= t.payee_id %></td>
              <td><%= link_to "Delete", t, method: "delete", confirm: "Are you Sure?" %></td>
            </tr>
          <% end %>
        <% else %>
          <h5>No debits found</h5>
        <% end %>
      </tbody>
      <tbody>
        <h3>Credits</h3>
        <% if @user.credits %>
          <% @user.credits.each do |t| %>
            <tr>
              <td><%= t.amount %></td>
              <td><%= t.created_at %></td>
              <td><%= t.description %></td>
              <td><%= t.payer_id %></td>
              <td><%= t.payee_id %></td>
              <td><%= link_to "Delete", t, method: "delete", confirm: "Are you Sure?" %></td>
            </tr>
          <% end %>
        <% else %>
          <h5>No credits found</h5>
        <% end %>
      </tbody>
  </table>
</div>

app/views/transactions/new.html.erb
<h2>Create a new IOU</h2>

<%= form_for @transaction, url: { action: "create" } do |f|  %>
  <h3>Pick a User</h3>
  <p>
    <%= f.label :payer_id, "Payer" %>
    <%= select("transaction", "payer_id", User.all.collect {|u| [ u.email, u.id ] }, {include_blank: 'None'})
    %>
  </p>
  <p>
    <%= f.label :payee_id, "Payee" %>
    <%= select("transaction", "payee_id", User.all.collect {|u| [ u.email, u.id ] }, {include_blank: 'None'})
    %>
  </p>
  <p>
    <%= f.label :amount, "Amount" %>
    <%= f.text_field :amount %>
  </p>
    <%= f.submit "Create" %>
<% end %>

app/views/users/index.html.erb
<h3>Find a friend!</h3>
<% if @users %>
  <% @users.each do |user| %>
    <li><%= user.email %></li>
  <% end %>
<% else %>
  <h4>No other users present</h4>
<% end %>